name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          set +e
          $CC ./build/nobuild.c -o ./build/nobuild
          ./build/nobuild --release
          if [[$? == 2]]; then
            exit 0
          fi
          set -e
          echo "there was an issue with nobuild"
          exit 1
        env:
          AR: ar
          LD: ld
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          set +e
          $CC ./build/nobuild.c -o ./build/nobuild
          ./build/nobuild --release 
          if [[$? == 2]]; then
            exit 0
          fi
          set -e
          echo "there was an issue with nobuild"
          exit 1
        env:
          AR: llvm-ar
          LD: llvm-link
          CC: clang
          CXX: clang++
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          set +e
          $CC ./build/nobuild.c -o ./build/nobuild
          ./build/nobuild --release
          if [[$? == 2]]; then
            exit 0
          fi
          set -e
          echo "there was an issue with nobuild"
          exit 1
        env:
          AR: llvm-ar
          LD: llvm-link
          CC: clang
          CXX: clang++
